# Generated by Django 5.0.2 on 2024-04-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_history',
            old_name='name',
            new_name='username',
        ),
    ]
