# Generated by Django 5.0.2 on 2024-04-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0002_rename_name_user_history_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_history',
            name='skills',
        ),
    ]
