# Generated by Django 5.0.2 on 2024-04-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0003_remove_user_history_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_history',
            name='user_course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_history',
            name='user_industry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_history',
            name='user_interest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_history',
            name='user_skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
