# Generated by Django 5.0.2 on 2024-04-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0006_predictionresult_delete_prediction_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionresult',
            old_name='career',
            new_name='career_one',
        ),
        migrations.RemoveField(
            model_name='predictionresult',
            name='user',
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='career_three',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='career_two',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
