# Generated by Django 5.0.2 on 2024-04-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0007_rename_career_predictionresult_career_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_number', models.IntegerField()),
                ('career_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PredictionResult',
        ),
    ]
