# Generated by Django 5.0.2 on 2024-04-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0008_careerresult_delete_predictionresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CareerResult',
            new_name='PredictionResult',
        ),
    ]
