# Generated by Django 5.0.2 on 2024-04-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0009_rename_careerresult_predictionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='career_name',
        ),
        migrations.RemoveField(
            model_name='predictionresult',
            name='result_number',
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='career_one',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='career_three',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='career_two',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
