# Generated by Django 5.0.2 on 2024-04-26 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0010_remove_predictionresult_career_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='user_history',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='thesisapp.userhistory'),
        ),
    ]
