# Generated by Django 5.0.2 on 2024-04-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0011_predictionresult_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='user_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thesisapp.userhistory'),
        ),
    ]
