# Generated by Django 5.0.2 on 2024-04-26 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0012_alter_predictionresult_user_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='user_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_results', to='thesisapp.userhistory'),
        ),
    ]
