# Generated by Django 5.0.2 on 2024-04-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0014_alter_predictionresult_user_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='user_history',
        ),
    ]
