# Generated by Django 5.0.2 on 2024-04-29 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0015_remove_predictionresult_user_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
