# Generated by Django 5.0.2 on 2024-04-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0017_predictionresult_user_history_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='user_history_id',
        ),
    ]
