# Generated by Django 4.2.7 on 2024-04-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0018_remove_predictionresult_user_history_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('skills', models.CharField(max_length=100, null=True)),
                ('course', models.CharField(max_length=100, null=True)),
                ('industry', models.CharField(max_length=100, null=True)),
                ('interest', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
