# Generated by Django 4.2.7 on 2024-04-30 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesisapp', '0019_userhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='course',
            new_name='user_course',
        ),
        migrations.RenameField(
            model_name='userhistory',
            old_name='industry',
            new_name='user_industry',
        ),
        migrations.RenameField(
            model_name='userhistory',
            old_name='interest',
            new_name='user_interest',
        ),
        migrations.RenameField(
            model_name='userhistory',
            old_name='skills',
            new_name='user_skills',
        ),
    ]
